# Generated by Django 5.0.4 on 2024-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('no_of_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('trip', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
